services:
  api:
    container_name: financial_api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ${ENV_FILE:-.env}
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: financial_postgres
    image: postgres:16
    env_file:
      - ${ENV_FILE:-.env}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
     test: ["CMD-SHELL", "pg_isready"]
     interval: 5s
     timeout: 5s
     retries: 10
     start_period: 5s

volumes:
  postgres_data: