name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint
        run: |
          docker compose run --rm api ruff check .

      - name: Build containers
        run: |
          docker compose build

      - name: Run tests
        run: |
          ENV_FILE=.env.test docker compose run --rm api pytest

      - name: Stop containers
        if: always()
        run: |
          ENV_FILE=.env.test docker compose down -v